First version on github
Cleaned up the code by removing the permute function, which was not
doing anything. It might be interesting to implement jumbling in some
future version, but for now the code needs to be streamlined. The
interface was also changed slightly, and the documentation written.

Change log up to this version:

- Version 0.1
  - First running version.
- Version 0.2 (December 6, 2012)
  - Compute average distances in case input matrix not symmetrical.
- Version 0.3 (February 6, 2013)
  - Allocated 512 instead of 256 bytes in
    distTree.c:  mat->label[t] = (char *)emalloc(512*sizeof(char));
    This removed a segmentation fault. However, \ty{valgrind.sh} shows
    that there seem to be problems with the initialization of
    variables.
  - Possibly related problem:
    ./cluster ../../Data/ecoli.dis | new2view
    error: syntax error
- Version 0.4 (December 12, 2014)
  - The syntax error above is gone (I have worked on cluster and
    new2view and am not quite sure how the error finally vanished).
  - Fixed the initialization problem flagged by valgrind.
  - Corrected tree printing.
  - Renamed program to clustDist.
  - Changed dangerous strcat to strncat in distTree.constrTree.
- Version 0.5 (January 5, 2015)
  - Fixed error in tree computation when applied to distance matrix of
    2010 E. coli genomes by ensuring that no negative distances
    are computed; see line 220 in distTree.c (function
    recalcDist).
  - Fixed a memory error due to strncat in line 156 of distTree.c.
- Version 0.6 (June 11, 2015)
  - Allowed looping over multiple distance matrices.
  - In phylip the order of taxa is jumbled if more than one
    distance matrix is analyzed. I have tried to implement this in the
    function permute, but this clashes with cluster in some way
    that I don't understand yet. So for the time being jumbling is
    switched off.
- Version 0.7 (June 24, 2015)
  - Fixed deallocation of random number generator, which was a leftover
    from my failed attempt in version 0.6 to implement jumbling of taxa
    for multiple distance files.
- Version 0.8 (November 6, 2018)
  - Fixed bug in interface.c.
- Version 0.9 (May 20, 2019)
  - Removed unnecessary initialization of random number generation in scanFile.